### PR TITLE
1136 delete image from library

### PR DESCRIPTION
**Pull request by pkimber**
:sparkles: @mdinsmore @gbushell @timitee

I have rewritten the image wizard using standard views:
- [x] I have added an image library to settings.
- [x] If a member of staff goes to settings, image library, they can choose to delete one or more images.
- [x] Each image can be assigned to a category.
- [x] When choosing an image, the user can view all images or select a category.

I still have to implement multi-select for the image wizard:
- [ ] Would it be acceptable to add one image at a time to a slideshow - or do we need multi-select?
- [ ] How important is image ordering in the slideshow (we do have a customer request)?  To implement image ordering within a slideshow, I will need an intermediate model between the content and the image.  The intermediate model would have an `order` field.

I still have to convert the link wizard to use standard views!

### CODE REVIEW

**Comment by pkimber** [comment]
Discussed with Greg
- We will put a preview of the image/slideshow on the first (option) page.
- When adding images for a slideshow, we will return to the option page each time.
- To remove images from a slideshow, we will click the remove link on the option page.  This will take us to a view showing current images with a tick-box to allow removal of any or all images.
- For slideshows, we will add a back button and a finish button to the option page.  Clicking one of these buttons will return us to the page in design mode.

**Comment by pkimber** [comment]
@mdinsmore If you have time, this pull request is ready for review.  I have moved the image and link wizard to standard views.  I am getting tired of it, so it could do with a review :eyeglasses: :sparkles: 
Thank you

**Comment by mdinsmore** [comment]
It works well...  It's a lot more flexible that the wizard version

I had an issue with publishing a slide show - the publish page does not show the slide show and also I get the following error when I click publish
    AttributeError at /title/4/publish/

```
Cannot use add() on a ManyToManyField which specifies an intermediary model. Use 
example_block.TitleImage's Manager instead.
```

A couple of things that occurred to me:
- Should you be able to remove an image from the library i.e. make it not visible without marking it as deleted - similar to the "Add to image library" tick box when uploading an imge ?
- What about giving access to the Image library / define categories from the first page of the image wizard as well as settings or is it better to have it focused?
- If you have a lot of categories then you have to scroll to see the the whole library and upload an image options

**Comment by mdinsmore** [comment]
just pulled the latest commit and the publish issue is fixed

**Pull request merged**
